export interface AppointmentFull {
  id: number
  patient: string
  patientInitials: string
  patientAge: number
  patientPhone: string
  doctor: string
  doctorSpecialty: string
  treatment: string
  date: string
  time: string
  duration: string
  status: "confirmada" | "pendiente" | "en-curso" | "completada" | "cancelada"
  notes: string
  cost: string
}

export const allAppointments: AppointmentFull[] = [
  {
    id: 1,
    patient: "Maria Garcia Lopez",
    patientInitials: "MG",
    patientAge: 34,
    patientPhone: "+52 55 1234 5678",
    doctor: "Dr. Carlos Mendez",
    doctorSpecialty: "Odontologia General",
    treatment: "Limpieza dental",
    date: "12 Feb 2026",
    time: "09:00",
    duration: "30 min",
    status: "completada",
    notes: "Limpieza rutinaria semestral. Recomendar hilo dental.",
    cost: "$800",
  },
  {
    id: 2,
    patient: "Juan Rodriguez Perez",
    patientInitials: "JR",
    patientAge: 45,
    patientPhone: "+52 55 2345 6789",
    doctor: "Dra. Ana Torres",
    doctorSpecialty: "Cirugia Oral",
    treatment: "Extraccion molar",
    date: "12 Feb 2026",
    time: "09:30",
    duration: "45 min",
    status: "en-curso",
    notes: "Tercer molar inferior derecho. Revision previa de radiografia.",
    cost: "$2,500",
  },
  {
    id: 3,
    patient: "Sofia Martinez Ruiz",
    patientInitials: "SM",
    patientAge: 28,
    patientPhone: "+52 55 3456 7890",
    doctor: "Dr. Luis Herrera",
    doctorSpecialty: "Ortodoncia",
    treatment: "Ortodoncia - Ajuste",
    date: "12 Feb 2026",
    time: "10:00",
    duration: "20 min",
    status: "confirmada",
    notes: "Ajuste mensual de brackets. Revision de avance.",
    cost: "$600",
  },
  {
    id: 4,
    patient: "Pedro Sanchez Diaz",
    patientInitials: "PS",
    patientAge: 52,
    patientPhone: "+52 55 4567 8901",
    doctor: "Dra. Elena Rios",
    doctorSpecialty: "Endodoncia",
    treatment: "Endodoncia",
    date: "12 Feb 2026",
    time: "10:30",
    duration: "60 min",
    status: "pendiente",
    notes: "Segundo premolar superior. Paciente con hipertension controlada.",
    cost: "$4,200",
  },
  {
    id: 5,
    patient: "Laura Fernandez Gil",
    patientInitials: "LF",
    patientAge: 31,
    patientPhone: "+52 55 5678 9012",
    doctor: "Dr. Carlos Mendez",
    doctorSpecialty: "Odontologia General",
    treatment: "Resina dental",
    date: "12 Feb 2026",
    time: "11:00",
    duration: "40 min",
    status: "confirmada",
    notes: "Restauracion de pieza 14. Caries mesial.",
    cost: "$1,200",
  },
  {
    id: 6,
    patient: "Roberto Alvarez Mora",
    patientInitials: "RA",
    patientAge: 39,
    patientPhone: "+52 55 6789 0123",
    doctor: "Dra. Ana Torres",
    doctorSpecialty: "Cirugia Oral",
    treatment: "Implante dental",
    date: "12 Feb 2026",
    time: "11:30",
    duration: "90 min",
    status: "confirmada",
    notes: "Primera fase de implante. Pieza 36.",
    cost: "$12,000",
  },
  {
    id: 7,
    patient: "Carmen Ruiz Hernandez",
    patientInitials: "CR",
    patientAge: 41,
    patientPhone: "+52 55 7890 1234",
    doctor: "Dr. Luis Herrera",
    doctorSpecialty: "Ortodoncia",
    treatment: "Ortodoncia - Revision",
    date: "12 Feb 2026",
    time: "13:00",
    duration: "20 min",
    status: "pendiente",
    notes: "Revision mensual. Evaluar necesidad de cambio de arco.",
    cost: "$600",
  },
  {
    id: 8,
    patient: "Isabel Gomez Luna",
    patientInitials: "IG",
    patientAge: 55,
    patientPhone: "+52 55 9012 3456",
    doctor: "Dr. Carlos Mendez",
    doctorSpecialty: "Odontologia General",
    treatment: "Corona dental",
    date: "12 Feb 2026",
    time: "14:00",
    duration: "50 min",
    status: "confirmada",
    notes: "Colocacion de corona definitiva en pieza 21.",
    cost: "$5,800",
  },
  {
    id: 9,
    patient: "Fernando Castillo Rey",
    patientInitials: "FC",
    patientAge: 37,
    patientPhone: "+52 55 0123 4567",
    doctor: "Dra. Ana Torres",
    doctorSpecialty: "Cirugia Oral",
    treatment: "Consulta valoracion",
    date: "12 Feb 2026",
    time: "14:30",
    duration: "30 min",
    status: "pendiente",
    notes: "Primera consulta. Evaluar terceros molares.",
    cost: "$500",
  },
  {
    id: 10,
    patient: "Diana Morales Castro",
    patientInitials: "DM",
    patientAge: 29,
    patientPhone: "+52 55 1122 3344",
    doctor: "Dra. Elena Rios",
    doctorSpecialty: "Endodoncia",
    treatment: "Endodoncia",
    date: "12 Feb 2026",
    time: "15:00",
    duration: "60 min",
    status: "confirmada",
    notes: "Retratamiento endodontico pieza 46.",
    cost: "$4,800",
  },
  {
    id: 11,
    patient: "Miguel Santos Flores",
    patientInitials: "MS",
    patientAge: 33,
    patientPhone: "+52 55 5566 7788",
    doctor: "Dr. Luis Herrera",
    doctorSpecialty: "Ortodoncia",
    treatment: "Ortodoncia - Colocacion",
    date: "13 Feb 2026",
    time: "09:00",
    duration: "90 min",
    status: "confirmada",
    notes: "Colocacion de brackets ceramicos superior e inferior.",
    cost: "$18,000",
  },
  {
    id: 12,
    patient: "Lucia Reyes Mendoza",
    patientInitials: "LR",
    patientAge: 48,
    patientPhone: "+52 55 9988 7766",
    doctor: "Dra. Elena Rios",
    doctorSpecialty: "Endodoncia",
    treatment: "Endodoncia",
    date: "13 Feb 2026",
    time: "10:00",
    duration: "60 min",
    status: "pendiente",
    notes: "Endodoncia en molar superior. Pulpitis irreversible.",
    cost: "$4,200",
  },
  {
    id: 13,
    patient: "Ana Vargas Romero",
    patientInitials: "AV",
    patientAge: 26,
    patientPhone: "+52 55 4455 6677",
    doctor: "Dr. Carlos Mendez",
    doctorSpecialty: "Odontologia General",
    treatment: "Blanqueamiento",
    date: "13 Feb 2026",
    time: "11:00",
    duration: "60 min",
    status: "confirmada",
    notes: "Blanqueamiento laser en consultorio.",
    cost: "$3,500",
  },
  {
    id: 14,
    patient: "Pablo Navarro Solis",
    patientInitials: "PN",
    patientAge: 44,
    patientPhone: "+52 55 2233 4455",
    doctor: "Dra. Elena Rios",
    doctorSpecialty: "Endodoncia",
    treatment: "Corona temporal",
    date: "11 Feb 2026",
    time: "10:00",
    duration: "30 min",
    status: "completada",
    notes: "Colocacion de corona temporal post-endodoncia.",
    cost: "$1,500",
  },
  {
    id: 15,
    patient: "Teresa Lozano Paz",
    patientInitials: "TL",
    patientAge: 60,
    patientPhone: "+52 55 6677 8899",
    doctor: "Dr. Carlos Mendez",
    doctorSpecialty: "Odontologia General",
    treatment: "Protesis parcial",
    date: "11 Feb 2026",
    time: "14:00",
    duration: "40 min",
    status: "completada",
    notes: "Ajuste de protesis parcial inferior.",
    cost: "$2,200",
  },
  {
    id: 16,
    patient: "Maria Garcia Lopez",
    patientInitials: "MG",
    patientAge: 34,
    patientPhone: "+52 55 1234 5678",
    doctor: "Dr. Carlos Mendez",
    doctorSpecialty: "Odontologia General",
    treatment: "Blanqueamiento",
    date: "10 Feb 2026",
    time: "09:00",
    duration: "60 min",
    status: "cancelada",
    notes: "Paciente cancelo por motivos personales. Reprogramar.",
    cost: "$3,500",
  },
]
